- name : configure the db module 
  hosts: db 
  become: true 
  vars: 
    mysql_root_passwd: ExpenseApp@1 
    login_host: db.78skedar.online
  vars_prompt:
    name: Mysql_root_password
    prompt: PLease enter the mysql root password 
    private: flase 
  gather_facts: yes 
  tasks:
    - name: install the mysql server 
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: enable and start the mysql
      ansible.builtin.service:
        name: mysqld 
        state: started
        enabled: yes 

    - name : Install  Python 3.9 specifically, using the 'pip3.9' executable
      ansible.builtin.pip:
       name: 
          - PyMySQL 
          - cryptography
       executable: pip3.9

    - name: check the myqsl root password setuped or not 
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_passwd }}"
        login_host: "{{ login_host }}"
        filter: version
      ignore_errors: yes 
      register: mysql

    - name: print the mysql info 
      ansible.builtin.debug:
        msg: "mysql info is {{ mysql }}"
        
    - name: please setup the password 
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
      when: mysql.failed is true 
    