- name : configure the frount end
  hosts: frontend
  become: yes 
  gather_facts: no 
  tasks:
    - name : install the nginx server
      ansible.builtin.dnf:
        name: nginx
        state: latest 
    - name: start and enable the nginx server 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes 

    - name: remove the default content in html dir 
      ansible.builtin.file: 
        path: /usr/share/nginx/html
        state: absent 

    - name: crete html dir
      ansible.builtin.file: 
        path: /usr/share/nginx/html
        state: directory 

    - name: downlode the code and unzip the /usr/share/nginx/html in htis path 
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes 

    - name: copy the expense conf file to the /etc/nginx/defaul.d/expense.conf 
      ansible.builtin.copy: 
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf 
        remote_src: yes 
